version: "3"
services:
  
  ui:
   build:
      context: ./frontend
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: mern-ui
   networks:
    -  mern-stack-net
   volumes:
    -  ./frontend/src:/usr/app/src
    -  ./frontend/public:/usr/app/public
   depends_on:
    - api
   stdin_open: true
   tty: true

  api:
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
     - 5000:5000
   container_name: mern-api
   networks:
     - mern-stack-net
   volumes:
    - ./backend/src:/usr/app/src
   depends_on:
    - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local